
(defun my/close_shell ()
  (interactive)
  (lexical-let (init_wd wds)
    (setq init_wd (selected-window))
    (setq wds (window-list))
    (while wds
      (when (string-match "*Shell Command Output*" (format "%s" (car wds)))
        (if (equal (car wds) init_wd) (setq init_wd (next-window init_wd)))
        (select-window (car wds))
        (delete-window)
        )
      (setq wds (cdr wds))
      )
    (select-window init_wd)
    )
)

(defun my/open_shell ()
  (interactive)
  (when (not (string-match "*Shell Command Output*" (format "%s" (window-list))))
    (split-window-right)
    (other-window 1)
    (switch-to-buffer "*Shell Command Output*")
    (other-window -1)
    )
)

(keymap-global-set "C-;" 'my/close_shell)
(keymap-global-set "C-:" 'my/open_shell)
