#+title: Emacs Configuration

* Configure =use-package=

I use =use-package= to install and configure my packages.

I should be able to open Emacs for the first time and have my whole environment automatically installed. I'm not /totally/ sure about that, but we're gettin' close.

#+begin_src emacs-lisp
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+end_src

Add =:vc= to =use-package=

#+begin_src emacs-lisp
    (unless (package-installed-p 'vc-use-package)
        (package-vc-install "https://github.com/slotThe/vc-use-package"))
    (require 'vc-use-package)
#+end_src

Defer loading packages unless explicitly demanded.

#+begin_src emacs-lisp
  (setq use-package-always-defer t)
#+end_src

Always compile packages, and use the newest version available.

#+begin_src emacs-lisp
  (use-package auto-compile
    :ensure t
    :demand t
    :config (auto-compile-on-load-mode))

  (setq load-prefer-newer t)
#+end_src

Disable deprecation warnings about =cl=. The =cl= library has been deprecated, but lots of packages still use it. I can't control that, but I can disable the warnings.

#+begin_src emacs-lisp
  (setq byte-compile-warnings '(cl-functions))
#+end_src

Don't pop up a buffer to warn me about deprecations and other minor issues.

#+begin_src emacs-lisp
  (setq warning-minimum-level :emergency)
#+end_src

* Use =sensible-defaults.el=

Use [[https://github.com/hrs/sensible-defaults.el][sensible-defaults.el]] for some basic settings.

#+begin_src emacs-lisp
  (use-package sensible-defaults
    :ensure t
    :vc (:url "https://github.com/hrs/sensible-defaults.el.git"
              :rev :newest)
    :demand t

    :config
    (sensible-defaults/use-all-settings)
    (sensible-defaults/use-all-keybindings)
    (sensible-defaults/backup-to-temp-directory))
#+end_src

* UI preferences

Ask before quit
#+begin_src emacs-lisp
  (setq confirm-kill-emacs #'y-or-n-p)
#+end_src

** Don't resize the frame

By default, Emacs attempts to resize each frame to maintain a certain number of characters in each line, so this width varies depending on the font used. This operation is a bit expensive, and since I use =hyprland=, a tiling window manager, it's also completely unnecessary, since the frame will be resized differently regardless. Just skip the whole thing instead.

#+begin_src emacs-lisp
  (setq frame-inhibit-implied-resize t)
#+end_src

** Tweak window chrome

I don't usually use the menu or scroll bar, and they take up useful space.

#+begin_src emacs-lisp
  (tool-bar-mode 0)
  (scroll-bar-mode -1)
#+end_src

There's a tiny scroll bar that appears in the minibuffer window. This disables that:

#+begin_src emacs-lisp
  (set-window-scroll-bars (minibuffer-window) nil nil)
#+end_src

Add line number

#+begin_src emacs-lisp
  (global-display-line-numbers-mode t)
#+end_src

Add column number

#+begin_src emacs-lisp
  (setq column-number-mode t)
#+end_src

** Disable the visible bell

#+begin_src emacs-lisp
  (setq visible-bell nil)
  (setq ring-bell-function 'ignore)
#+end_src

** Enable smooth scrolling

This is especially nice when I use a mouse.

#+begin_src emacs-lisp
  (pixel-scroll-precision-mode 1)

  (defvar +scroll-delta 180)

  (defun +scroll-up-some ()
    (interactive)
    (pixel-scroll-precision-scroll-up +scroll-delta))

  (defun +scroll-down-some ()
    (interactive)
    (pixel-scroll-precision-scroll-down +scroll-delta))


  (global-set-key (kbd "C-M-<up>") '+scroll-up-some)
  (global-set-key (kbd "C-M-<down>") '+scroll-down-some)
#+end_src

** Configure a pretty modeline

#+begin_src emacs-lisp
  (use-package moody
    :demand t

    :custom
    (x-underline-at-descent-line t)

    :config
    (moody-replace-mode-line-buffer-identification)
    (moody-replace-vc-mode)
    (moody-replace-eldoc-minibuffer-message-function))
#+end_src


** Load up a theme

This sets up the current theme.

#+begin_src emacs-lisp
  (setq custom-theme-directory
        (concat user-emacs-directory "themes"))

  (load-theme 'witchhazel t)

  (use-package catppuccin-theme
    :ensure t
    :demand t
    :custom
    (catppuccin-flavor 'macchiato)

    :config
    (catppuccin-reload))
#+end_src

** Use =minions= to hide all minor modes

I never want to see a minor mode, and manually adding =:diminish= to every use-package declaration is a hassle. This uses =minions= to hide all the minor modes in the modeline. Nice!

#+begin_src emacs-lisp
  (use-package minions
    :ensure t
    :demand t

    :custom
    (minions-mode-line-delimiters (cons "" ""))

    :config
    (defun +set-minions-mode-line-lighter ()
      (setq minions-mode-line-lighter
            (if (display-graphic-p) "⚙" "#")))

    (add-hook 'server-after-make-frame-hook #'+set-minions-mode-line-lighter)

    (minions-mode 1))
#+end_src

** Scroll conservatively

When point goes outside the window, Emacs usually recenters the buffer point.
This changes scrolling behavior to only scroll 10 lines.

#+begin_src emacs-lisp
  (setq scroll-conservatively 0)
  (setq scroll-step 10)
#+end_src

** Set font and configure font resizing

#+begin_src emacs-lisp
  (defvar +font-size-fixed 105)
  (defvar +font-size-variable 95)

  (set-face-attribute 'default nil
                      :family "JetBrains Mono"
                      :height +font-size-fixed)

  (set-face-attribute 'fixed-pitch nil
                      :family "JetBrains Mono"
                      :height +font-size-fixed)

  (set-face-attribute 'variable-pitch nil
                      :family "Minion Pro"
                      :height +font-size-variable)

  (use-package default-text-scale
    :ensure t
    :bind
    (("C-)" . default-text-scale-reset)
     ("C-=" . default-text-scale-increase)
     ("C--" . default-text-scale-decrease)))
#+end_src

** Highlight the current line

=global-hl-line-mode= softly highlights the background color of the line containing point. It makes it a bit easier to find point, and it's useful when pairing or presenting code.

#+begin_src emacs-lisp
  (global-hl-line-mode)
#+end_src

** Highlight uncommitted changes

Use the =diff-hl= package to highlight changed-and-uncommitted lines when programming.

#+begin_src emacs-lisp
  (use-package diff-hl
    :ensure t
    :config
    :hook ((text-mode prog-mode vc-dir-mode) . turn-on-diff-hl-mode))
#+end_src

* Project management

** =comint= (Command Interpreter)

Treat =comint= sessions more like a shell.

#+begin_src emacs-lisp
  (use-package comint-mode
    :ensure nil
    :bind (("C-l" . comint-clear-buffer)
           ("C-d" . +kill-current-buffer)))
#+end_src

** =completion-at-point=

Use =corfu= for a pop-up completions menu.

#+begin_src emacs-lisp
  (use-package corfu
    :ensure t
    :bind
    (:map corfu-map
          ("TAB" . corfu-next)
          ([tab] . corfu-next)
          ("S-TAB" . corfu-previous)
          ([backtab] . corfu-previous))

    :custom
    (tab-always-indent 'complete)
    (corfu-auto t)
    (corfu-cycle t)
    (corfu-on-exact-match 'insert)
    (corfu-preselect 'prompt)

    :init
    (global-corfu-mode))
#+end_src

** =ediff=

When using =ediff= to compare file, show files side by side and don't split the control panel into a separate frame.

#+begin_src emacs-lisp
  (use-package ediff
    :ensure t
    :config
    (setq ediff-window-setup-function 'ediff-setup-windows-plain)
    (setq ediff-split-window-function 'split-window-horizontally))
#+end_src

** git

- I bring up the status menu with =C-x g=.
- Per [[http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html][tpope's suggestions]], highlight commit text in the summary line that goes beyond 50 characters.
- Always take up the whole frame. I'm often on a laptop, where this is especially convenient, but generally I want additional git-related space more than I want more windows.

#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :ensure-system-package (git git-absorb)
    :bind ("C-x g" . magit-status)

    :config
    (use-package magit-section)
    (use-package with-editor)

    (require 'git-rebase)

    (defun +changed-files-on-branch (&optional directory)
      "Return a list of files that have changed on this branch (relative to main) relative to DIRECTORY."
      (let ((default-directory (or directory (project-root (project-current)))))
        (seq-remove #'string-empty-p
                    (split-string (shell-command-to-string "git diff --name-only main")
                                  "\n"))))

    (transient-replace-suffix 'magit-commit 'magit-commit-autofixup
      '("x" "Absorb changes" magit-commit-absorb))

    (setq git-commit-summary-max-length 50
          magit-bury-buffer-function 'magit-restore-window-configuration
          magit-display-buffer-function 'magit-display-buffer-fullframe-status-topleft-v1))
#+end_src

=git-timemachine= lets you quickly page through the history of a file.

#+begin_src emacs-lisp
  (use-package git-timemachine
    :ensure t)
#+end_src

** =project.el=

- Bind searching within the project to =C-c v=.
- Treat a directory containing =.dir-locals.el= as a project root (useful for projects not under version control).
- When I switch projects, just open a =dired= buffer at the project root rather than asking whether I want to open a file, search, etc.

#+begin_src emacs-lisp
  (use-package deadgrep
    :ensure t)

  (use-package project
    :ensure t
    :bind (("C-c v" . deadgrep)
           ("C-x p p" . +project-switch-project))

    :custom
    (project-vc-extra-root-markers '(".dir-locals.el"))

    :config
    (defun +project-switch-project (dir)
      (interactive (list (project-prompt-project-dir)))
      (dired dir)))
#+end_src

* Programming environments

Tabs are displayed as 8 characters by default. This reduces that.

#+begin_src emacs-lisp
  (setq-default tab-width 4)
#+end_src

Treating terms in CamelCase symbols as separate words makes editing a little easier for me, so I like to use =subword-mode= everywhere.

#+begin_src emacs-lisp
  (use-package subword
    :ensure t
    :config (global-subword-mode 1))
#+end_src

Compilation output goes to the =*compilation*= buffer. I rarely have that window selected, so the compilation output disappears past the bottom of the window. This automatically scrolls the compilation window so I can always see the output.

#+begin_src emacs-lisp
  (setq compilation-scroll-output t)
#+end_src

** =which-key=

#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :config (which-key-mode))
#+end_src

** =lsp-mode=

FIXME :
I'm using =lsp-mode= to manage my LSP servers.
change to eglot

#+begin_src emacs-lisp
  ;; (use-package lsp-mode
  ;;   :ensure t
  ;;   :defer t
  ;;   :hook ((lsp-mode . lsp-enable-which-key-integration)
  ;; 	 (lsp-mode . (lambda ()
  ;; 		       (let ((lsp-keymap-prefix "C-c l"))
  ;; 			 (lsp-enable-which-key-integration)))))
  ;;   ;; :init
  ;;   ;; (setq lsp-keep-workspace-alive nil
  ;;   ;; 			lsp-signature-doc-lines 5
  ;;   ;; 			lsp-idle-delay 0.5
  ;;   ;; 			lsp-prefer-capf t)
  ;;   :config
  ;;   (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)))
#+end_src

** =eglot=
I'm using the built-in =eglot= to manage my LSP servers.

#+begin_src emacs-lisp
  (use-package eglot
    :ensure t
    :hook (((c-mode) . eglot-ensure))
    :config
    (defun +eglot-format-buffer-on-save ()
      (add-hook 'before-save-hook #'eglot-format-buffer -10 t)))
#+end_src

** =direnv=

#+begin_src emacs-lisp
  (use-package direnv
    :ensure t
    ;;:custom
    ;;(direnv-always-show-summary nil)

    :config
    (direnv-mode))
#+end_src

** Toggle code folding

I use =BACKTAB= to toggle hiding blocks of code.

Similarly, I bind =C-BACKTAB= to toggle hiding /all/ the top-level code blocks.

#+begin_src emacs-lisp
  (use-package hs-minor-mode
    :ensure nil
    :hook prog-mode
    :bind (("<backtab>" . hs-toggle-hiding)
           ("C-<backtab>" . +toggle-all-folds))

    :init
    (defvar-local +maybe-hidden-blocks nil)
    (add-hook 'hs-hide-hook (lambda () (setq-local +maybe-hidden-blocks t)))

    (defun +toggle-all-folds ()
      "If any block are hidden, show them all. Otherwise, hide all top-level blocks."
      (interactive)
      (if +maybe-hidden-blocks
          (progn
            (setq-local +maybe-hidden-blocks nil)
            (hs-show-all))
        (hs-hide-all))))
#+end_src

** =cron=

Add syntax highlighting to =cron= files.

#+begin_src emacs-lisp
  (use-package crontab-mode
    :ensure t)
#+end_src

** CSS & Sass

Indent by 2 spaces.

#+begin_src emacs-lisp
  (use-package css-mode
    :ensure t
    :config
    (setq css-indent-offset 4))
#+end_src

Don't compile the current SCSS file every time I save.

#+begin_src emacs-lisp
  (use-package scss-mode
    :ensure t
    :config
    (setq scss-compile-at-save nil))
#+end_src

** JavaScript & TypeScript

Use LSP with JS.

#+begin_src emacs-lisp
  (use-package js-mode
    :ensure nil
    :hook (js-mode . eglot-ensure))
#+end_src

Browse JSON documents hierarchically with =json-navigator-navigate-after-point=.

#+begin_src emacs-lisp
  (use-package json-navigator
    :commands (json-navigator-navigate-after-point))
#+end_src

** Java

Use LSP with java.

#+begin_src emacs-lisp
  (setq eldoc-echo-area-use-multiline-p nil)
  (use-package eldoc-box
    :ensure t)

  (use-package java-mode
    ;; :ensure t
    :hook (java-mode . eglot-ensure))

  (defun tkj/default-code-style-hook()
    (setq c-basic-offset 2
          c-label-offset 0
          indent-tabs-mode nil
          require-final-newline t))
  (add-hook 'java-mode-hook 'tkj/default-code-style-hook)

  (defun my-java-mode-hook ()
    (auto-fill-mode)
    ;; (flycheck-mode)
    ;; (yas-minor-mode)
    (when window-system
      (set-fringe-style '(8 . 0)))

    ;; Fix indentation for anonymous classes
    (c-set-offset 'substatement-open 0)
    (if (assoc 'inexpr-class c-offsets-alist)
        (c-set-offset 'inexpr-class 0))

    ;; Indent arguments on the next line as indented body.
    (c-set-offset 'arglist-intro '++))
  (add-hook 'java-mode-hook 'my-java-mode-hook)

  (defun tkj/java-run-junit-at-point ()
    "Run the JUnit test method or class at point."
    (interactive)
    (let* ((method-name (thing-at-point 'symbol t))
           (class-name (file-name-sans-extension (file-name-nondirectory buffer-file-name)))
           (pom-file (locate-dominating-file (or (buffer-file-name) default-directory) "pom.xml")))
      (if (and method-name class-name pom-file)
          (let* ((default-directory (file-name-directory pom-file))
                 (test-param (if (string-equal class-name method-name)
                                 class-name
                               (format "%s#%s" class-name method-name)))
                 (command (format "mvn --batch-mode --file %s test -Dtest=%s"
                                  (expand-file-name "pom.xml" pom-file)
                                  test-param)))
            (compilation-start command 'compilation-mode
                               `(lambda (_) (format "Run JUnit: %s" ,test-param))))
        (message "Unable to determine method, class, or pom.xml file."))))
  (add-hook 'java-mode-hook (lambda () (local-set-key (kbd "C-c t") #'tkj/java-run-junit-at-point)))

  (defun tkj/java-decompile-class ()
    "Run the FernFlower decompiler on the current .class file using
   fernflower, and opens the decompiled Java file."
    (interactive)
    (let* ((current-file (buffer-file-name))
           (output-dir (concat (file-name-directory current-file) "decompiled/"))
           (decompiled-file (concat output-dir (file-name-base current-file) ".java"))
           (command (format "fernflower %s %s"
                            (shell-quote-argument current-file)
                            (shell-quote-argument output-dir))))
      (if (and current-file (string-equal (file-name-extension current-file) "class"))
          (progn
            (unless (file-directory-p output-dir)
              (make-directory output-dir t))
            (message "Running FernFlower decompiler...")
  					(if (not (eq (shell-command command) 0)) (message (format "Command %s return an error" command))
  						(if (file-exists-p decompiled-file)
  								(find-file decompiled-file)
  							(message "Error: Decompiled file not found at %s" decompiled-file))))
        (message "Error: This command can only be run on .class files"))))
#+end_src

** Lisps

=rainbow-delimiters= is convenient for coloring matching parentheses.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :hook ((emacs-lisp-mode lisp-mode racket-mode) . rainbow-delimiters-mode))
#+end_src

*** Emacs Lisp

If I'm writing in Emacs Lisp I'd like to use =eldoc-mode= to display documentation.

#+begin_src emacs-lisp
  (use-package eldoc
    :ensure t
    :hook (emacs-lisp-mode . eldoc-mode))
#+end_src

Bind running tests to =C-c , v=, like in =rspec-mode=.

#+begin_src emacs-lisp
  (use-package ert
    :ensure nil
    :bind (:map emacs-lisp-mode-map ("C-c , v" . +ert-verify))

    :config
    (defun +ert-verify ()
      "Delete all loaded tests from the runtime, evaluate the
   current buffer and run all loaded tests with ert."
      (interactive)
      (ert-delete-all-tests)
      (eval-buffer)
      (ert 't)))
#+end_src

I use =package-lint= to verify that my packages are linted.

#+begin_src emacs-lisp
  (use-package package-lint
    :ensure t)
#+end_src

** OCaml

Use =tuareg-mode= for editing OCaml.

#+begin_src emacs-lisp
  (use-package tuareg
    :ensure t
    :ensure-system-package opam

    :config
    (electric-indent-mode 0))
#+end_src

Configure Merlin. This also requires installing the Merlin package through OPAM with =opam install merlin=.

#+begin_src emacs-lisp
  (use-package merlin
    :ensure t
    :after tuareg-mode
    :hook (tuareg-mode . merlin-mode))
#+end_src

** Python

#+begin_src emacs-lisp
  (use-package python-mode
    :ensure t
    :hook (python-mode . eglot-ensure))
#+end_src

Enable =elpy=. This provides automatic indentation, auto-completion, syntax checking, etc. Use the =python3= interpreter for eldoc.

#+begin_src emacs-lisp
  (use-package elpy
    :ensure t
    :after python-mode

    :custom
    (elpy-rpc-python-command "python3")

    :config
    (elpy-enable))
#+end_src

Format code according to PEP8 on save:

#+begin_src emacs-lisp
  (use-package py-autopep8
    :ensure t
    :after python-mode
    :hook (elpy-mode-hook . py-autopep8-enable-on-save))
#+end_src

** Rust

#+begin_src emacs-lisp
  (use-package rust-mode
    :hook (rust-mode . eglot-ensure))

  (add-hook 'rust-mode-hook #'+eglot-format-buffer-on-save)
#+end_src

** Shell

Indent with 2 spaces.

#+begin_src emacs-lisp
  (add-hook 'sh-mode-hook
            (lambda ()
              (setq sh-basic-offset 2
                    sh-indentation 2)))
#+end_src

** =web-mode=

Use =web-mode= with embedded Ruby files, regular HTML, and PHP.

#+begin_src emacs-lisp
  (use-package web-mode
    :ensure t
    :mode ("\\.erb$"
           "\\.html$"
           "\\.php$"
           "\\.rhtml$")

    :config
    (setq web-mode-markup-indent-offset 2
          web-mode-css-indent-offset 2
          web-mode-code-indent-offset 2
          web-mode-indent-style 2))
#+end_src

I'd like to see colors with =rainbow-mode=, so we'll need to install that, too:

#+begin_src emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :hook web-mode)
#+end_src

** Nix

#+begin_src emacs-lisp
  (use-package nix-mode
    :ensure t
    :hook (nix-mode . eglot-ensure))
#+end_src

* Terminal

I'm trying =vterm=. This disables =global-hl-line-mode= locally and lets me open up a new terminal instance with =C-c t=.

#+begin_src emacs-lisp
  (use-package multi-vterm
    :ensure t
    :ensure-system-package (cmake
                            ("/usr/share/doc/libvterm-dev" . libvterm-dev))
    :commands (multi-vterm)
    :hook (vterm-mode-hook . (lambda () (setq-local global-hl-line-mode nil)))

    :config
    (setq vterm-shell "/usr/bin/env zsh"))

  (global-set-key (kbd "C-c t") 'multi-vterm)
#+end_src

* Publishing and task management with Org-mode

- Put tags directly after the associated header rather than trying to align them.
- When hitting =C-<return>= to create a new heading, don't insert the heading between the current heading and its content, but instead append it /after/ the content.

#+begin_src emacs-lisp
  (use-package org
    :ensure t
    :custom
    (org-auto-align-tags nil)
    (org-footnote-auto-label nil)
    (org-footnote-section nil)
    (org-insert-heading-respect-content t)
    (org-tags-column 0)
    (add-hook 'org-mode-hook (org-redisplay-inline-images)))
#+end_src

Including =org-tempo= restores the =<s=-style easy templates that were deprecated in Org 9.2. This also adds a =<el= template to quickly insert a block of Emacs lisp.

#+begin_src emacs-lisp
  (use-package org-tempo
    :demand t
    :ensure nil

    :config
    (add-to-list 'org-structure-template-alist
                 '("el" . "src emacs-lisp")))
#+end_src

** =TeX= configuration

Automatically parse the file after loading it.
Enable a minor mode for dealing with math (it adds a few useful keybindings), and always treat the current file as the "main" file. That's intentional.

#+begin_src emacs-lisp
  (use-package auctex
    :ensure t
    :custom
    (TeX-parse-self t)

    :config
    (TeX-global-PDF-mode 1)

    (add-hook 'LaTeX-mode-hook
              (lambda ()
                (LaTeX-math-mode)
                (setq TeX-master t))))
#+end_src

* Mermaid org mode

#+begin_src emacs-lisp
  (use-package ob-mermaid
    :ensure t)

  (add-to-list 'org-babel-load-languages '(mermaid . t))
  (setq org-startup-with-inline-images t)
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images)
#+end_src

* Writing prose

I write prose in several modes: I might be editing an Org document, or a commit message, or an email. These are the main ones, with sub-items being /derived/ from their parents:

- =git-commit-mode=
- =text-mode=
  - =markdown-mode=
    - =gfm-mode=
  - =message-mode=
    - =mu4e-compose-mode=
  - =org-mode=

Recall that derived modes "inherit" their parent's hooks, so a hook added onto e.g. =text-mode= will also be executed by =mu4e-compose-mode=.

There are some exceptions, but I can usually associate a hook with every prose-related mode, so I store those in a list:

#+begin_src emacs-lisp
  (defvar prose-modes
    '(gfm-mode
      git-commit-mode
      markdown-mode
      message-mode
      mu4e-compose-mode
      org-mode
      text-mode))

  (defvar prose-mode-hooks
    (mapcar (lambda (mode) (intern (format "%s-hook" mode)))
            prose-modes))
#+end_src

** Activate =writing-mode=

This minor mode enables a distraction-free writing environment. It enables a whole bunch of pretty modes, switches fonts, enables inline images, and even displays the word count in the mode-line. Toggle it with =<f9>=.

#+begin_src emacs-lisp
  (use-package mixed-pitch)
  (use-package olivetti)
  (use-package org-appear :after org)
  (use-package org-modern :after org)
  (use-package org-superstar :after org)

  (use-package wc-mode
    :custom
    (wc-modeline-format "[%tw words]")

    :config
    (unbind-key "C-c C-w" wc-mode-map)
    (add-to-list 'minions-prominent-modes 'wc-mode))

  (use-package writing-mode
    :load-path "resources"
    :defer 1
    :hook (org-mode . writing-mode-repo)
    :bind (([f9] . writing-mode)
           ("<XF86Messenger>" . writing-mode)
           ("<XF86Tools>" . writing-mode))

    :config
    (require 'mixed-pitch)
    (require 'olivetti)
    (require 'org-appear)
    (require 'org-indent)
    (require 'org-modern)
    (require 'org-superstar)
    (require 'wc-mode)

    (defun writing-mode-repo () (writing-mode 1))

    (setq writing-enabled-modes
          '((org-mode . (org-appear-mode
                         org-indent-mode
                         org-modern-mode
                         org-superstar-mode))
            (elfeed-show-mode . (mixed-pitch-mode
                                 olivetti-mode))
            (special-mode . (mixed-pitch-mode
                             olivetti-mode))
            (text-mode . (mixed-pitch-mode
                          olivetti-mode
                          prettify-symbols-mode
                          visual-line-mode
                          wc-mode)))))

    (use-package publish-mode
      :load-path "resources"
      :bind ([f8] . publish-build-and-view-pdf)
      :config
      (setq publish-viewer-pdf "evince"))
#+end_src

** Editing with Markdown

Because I can't always use =org=.

- Associate =.md= files with GitHub-flavored Markdown.
- Use =pandoc= to render the results.
- Apply syntax highlighting in code blocks.
- Define a function to convert Markdown blocks to Org.

#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure-system-package pandoc
    :commands gfm-mode
    :mode (("\\.md$" . gfm-mode))
    :config
    (custom-set-faces
     '(markdown-pre-face ((t nil))))

    (setq markdown-command "pandoc --standalone --mathjax --from=gfm"
          markdown-disable-tooltip-prompt t
          markdown-fontify-code-blocks-natively t)

    (defun +markdown-to-org-region (start end)
      "Convert Markdown formatted text in region (START, END) to Org by
  shelling out to `pandoc'."
      (interactive "r")
      (shell-command-on-region start end
                               "pandoc -f markdown -t org --wrap=preserve" t t)))
#+end_src

** Cycle between spacing alternatives

Successive calls to =cycle-spacing= rotate between changing the whitespace around point to:

- A single space,
- No spaces, or
- The original spacing.

Binding this to =M-SPC= is strictly better than the original binding of =just-one-space=.

#+begin_src emacs-lisp
  (global-set-key (kbd "M-SPC") 'cycle-spacing)
#+end_src

** Enable region case modification

#+begin_src emacs-lisp
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil)
#+end_src

* Editing settings

** Always kill current buffer

Assume that I always want to kill the current buffer when hitting =C-x k=.

#+begin_src emacs-lisp
  (defun +kill-current-buffer ()
    "Kill the current buffer without prompting."
    (interactive)
    (kill-buffer (current-buffer)))

  (global-set-key (kbd "C-x k") '+kill-current-buffer)
#+end_src

** Set up =helpful=

The =helpful= package provides, among other things, more context in Help buffers.

#+begin_src emacs-lisp
  (use-package helpful
    :ensure t
    :commands (helpful-callable helpful-variable helpful-key)
    :bind
    ("C-h f" . helpful-callable)
    ("C-h v" . helpful-variable)
    ("C-h k" . helpful-key)

    :config
    (setq help-window-select t))
#+end_src

** Save my location within a file

Using =save-place-mode= saves the location of point for every file I visit. If I close the file or close the editor, then later re-open it, point will be at the last place I visited.

#+begin_src emacs-lisp
  (setq save-place-forget-unreadable-files nil)
  (save-place-mode 1)
#+end_src

** Always indent with spaces

Never use tabs. Tabs are the devil's whitespace.

#+begin_src emacs-lisp
  (setq-default indent-tabs-mode nil)
#+end_src

** Install and configure =which-key=

=which-key= displays the possible completions for a long keybinding. That's really helpful for some modes (like =project.el=, for example).

#+begin_src emacs-lisp
  (use-package which-key
    :demand t
    :ensure t
    :config (which-key-mode))
#+end_src

** Configure minibuffer completion

I'm trying =vertico=, =orderless=, =consult=, and =marginalia= as my completion framework.

#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :bind (:map vertico-map
                ("RET" . vertico-directory-enter)
                ("DEL" . vertico-directory-delete-char)
                ("M-DEL" . vertico-directory-delete-word))

    :init
    (vertico-mode))

  (use-package savehist
    :demand t
    :ensure t
    :init
    (savehist-mode))

  (use-package orderless
    :demand t
    :ensure t
    :custom
    (completion-styles '(orderless basic))
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles basic partial-completion)))))

  (use-package consult
    :ensure t
    :bind
    (("M-i" . consult-imenu)
     ("C-x b" . consult-buffer)
     ("C-x r b" . consult-bookmark)
     ("C-s" . consult-line))

    :config
    (setq completion-in-region-function #'consult-completion-in-region))

  (use-package marginalia
    :ensure t
    :bind (:map minibuffer-local-map
                ("M-A" . marginalia-cycle))

    :init
    (marginalia-mode))
#+end_src

** Switch and rebalance windows when splitting

When splitting a window, I invariably want to switch to the new window. This makes that automatic. Similarly, when closing a window I'd like to rebalance the remaining windows.

#+begin_src emacs-lisp
  (advice-add #'delete-window
              :after #'(lambda (&rest _)
                         (balance-windows)))

  (advice-add #'split-window
              :after #'(lambda (&rest _)
                         (balance-windows)
                         (other-window 1)))
#+end_src

** Mass editing of =grep= results

I like the idea of mass editing =grep= results the same way I can edit filenames in =dired=. These keybindings allow me to use =C-x C-q= to start editing =grep= results and =C-c C-c= to stop, just like in =dired=.

#+begin_src emacs-lisp
  (use-package wgrep
    :ensure t)

  (eval-after-load 'grep
    '(define-key grep-mode-map
      (kbd "C-x C-q") 'wgrep-change-to-wgrep-mode))

  (eval-after-load 'wgrep
    '(define-key grep-mode-map
      (kbd "C-c C-c") 'wgrep-finish-edit))

  (setq wgrep-auto-save-buffer t)
#+end_src

** Reformat typographic symbols and HTML entities to plain text

I sometimes need to convert some copied text containing typographic symbols like curly quotes and em-dashes into ASCII text. Similarly, I'll sometimes need to do that with HTML entities, too. This provides functions to do that within a specified region.

#+begin_src emacs-lisp
  (defvar +typographic-replacements
    '(("…" . "...")
      ("‘" . "'")
      ("’" . "'")
      ("“" . "\"")
      ("”" . "\"")
      ("–" . "--")
      ("—" . "---")))

  (defvar +html-entity-replacements
    '(("&amp;" . "&")
      ("&nbsp;" . " ")
      ("&lsquo;" . "'")
      ("&rsquo;" . "'")
      ("&apos;" . "'")
      ("&ldquo;" . "\"")
      ("&rdquo;" . "\"")
      ("&quot;" . "\"")
      ("&lt;" . "<")
      ("&gt;" . ">")))

  (defun +replace-symbols (replacements)
    (save-restriction
      (when (region-active-p)
        (narrow-to-region (region-beginning) (region-end)))
      (dolist (pair replacements)
        (goto-char (point-min))
        (while (search-forward (car pair) nil t)
          (replace-match (cdr pair))))))

  (defun +replace-typographic-symbols ()
    "Replace common typographic symbols in the region or buffer with their ASCII equivalents."
    (interactive)
    (+replace-symbols +typographic-replacements))

  (defun +replace-html-entities ()
    "Replace common HTML entities in the region or buffer with their ASCII equivalents."
    (interactive)
    (+replace-symbols +html-entity-replacements))
#+end_src

** Edit files as =sudo=

I always forget the TRAMP syntax, and this provides the easier-to-remember =sudo-edit= function.

#+begin_src emacs-lisp
  (use-package sudo-edit
    :commands (sudo-edit))
#+end_src

* Set custom keybindings

Just a few handy functions.

#+begin_src emacs-lisp
  ;(global-set-key (kbd "C-w") 'backward-kill-word)
  (global-set-key (kbd "M-o") 'other-window)
  (global-set-key (kbd "C-x C-o") 'other-window)
  (global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src

* Extra

Load any extra bits and bobs.

#+begin_src emacs-lisp
  (when (file-exists-p (concat user-emacs-directory "private.el"))
    (load-file (concat user-emacs-directory "private.el")))
#+end_src
